name: First Workflow
on: 
  push: 
    branches:
      - main
jobs: 
  first_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Printing name
        run: echo "pushed to main"
      - name: good bye
        run: echo "good bye"
      - name: listing files
        run: ls
