name: First Workflow
on: workflow_dispatch
jobs: 
  first_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Printing name
        run: echo "hello world"
      - name: good bye
        run: echo "good bye"
      - name: listing files
        run: ls
